# Generated by Django 2.0 on 2019-01-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20190112_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='fav_id',
        ),
        migrations.RemoveField(
            model_name='userlike',
            name='like_id',
        ),
    ]
