# Generated by Django 2.0 on 2019-01-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190112_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlike',
            options={'verbose_name': '用户点赞', 'verbose_name_plural': '用户点赞'},
        ),
    ]
