# Generated by Django 2.0 on 2019-01-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20190112_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comment',
            field=models.TextField(max_length=200, verbose_name='评论内容'),
        ),
    ]
