# Generated by Django 2.0 on 2019-01-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20190118_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecomments',
            name='comment',
            field=models.TextField(verbose_name='评论内容'),
        ),
    ]
