# Generated by Django 2.0 on 2019-01-22 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190118_1708'),
        ('operation', '0008_auto_20190119_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数量')),
                ('fav_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Blog', verbose_name='收藏的博客')),
            ],
            options={
                'verbose_name': '收藏数量',
                'verbose_name_plural': '收藏数量',
            },
        ),
        migrations.CreateModel(
            name='LikeCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_nums', models.IntegerField(default=0, verbose_name='点赞数量')),
                ('like_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Blog', verbose_name='点赞的博客')),
            ],
            options={
                'verbose_name': '点赞数量',
                'verbose_name_plural': '点赞数量',
            },
        ),
    ]
