# Generated by Django 2.0 on 2019-01-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20190127_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photh_type',
            field=models.CharField(choices=[('we', '我们'), ('gz', '广州'), ('sz', '深圳'), ('zh', '珠海'), ('fs', '佛山'), ('hd', '花都')], max_length=100, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='PhotoType',
        ),
    ]
