# Generated by Django 2.0 on 2019-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20190127_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='类型名称')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '图片的类型',
                'verbose_name_plural': '图片的类型',
            },
        ),
        migrations.AlterField(
            model_name='photo',
            name='photh_type',
            field=models.CharField(max_length=200, verbose_name='类型'),
        ),
    ]
