# Generated by Django 2.0 on 2019-01-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20190127_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photh_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.PhotoType', verbose_name='类型'),
        ),
    ]
