# Generated by Django 2.0 on 2019-01-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190112_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-add_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
