# Generated by Django 2.0 on 2019-01-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190118_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fav_nums',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='like_nums',
        ),
    ]
