# Generated by Django 2.0 on 2019-01-30 07:54

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190122_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='课程内容'),
        ),
    ]
