# Generated by Django 2.0 on 2019-04-03 21:48

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190327_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar\\default.jpg', null=True, upload_to=users.models.user_directory_path, verbose_name='头像'),
        ),
    ]
